[workspace]
members = ["programs/claim"]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "s"

[replace]
"toml_edit:0.23.2" = { version = "0.23.2" }
"toml_datetime:0.7.2" = { version = "0.7.2" }
