[workspace]
members = ["programs/claim"]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "s"

[dependencies]
# Force older versions that work with Solana's sbf Rust (1.75.0-dev)
indexmap      = "=2.2.6"
toml_edit     = "=0.21.1"
toml_datetime = "=0.6.3"
toml_parser   = "=0.6.3"
