[workspace]
members = ["programs/claim"]
resolver = "2"        # <â€” add this

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "s"

[patch.crates-io]
toml_edit = { version = "=0.22.9", package = "toml_edit" }
toml_datetime = { version = "=0.7.2", package = "toml_datetime" }
