[workspace]
members = ["programs/claim"]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "s"

[patch.crates-io]
# Force an indexmap version that compiles on rustc 1.75.0-dev (Solana BPF)
indexmap = "=2.0.0"
