[package]
name = "claim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "claim"

[dependencies]
anchor-lang = "0.29.0"

[patch.crates-io]
toml_edit = { version = "=0.22.9", package = "toml_edit" }
toml_datetime = { version = "=0.7.2", package = "toml_datetime" }
